global g_date
global g_predLoad
global g_lowerPI
global g_upperPI
global g_num_ESS
global g_Battery_cap
global g_currentSOC
global g_min_SOC
global g_max_SOC
global g_PSC_ch_cap
global g_PSC_disch_cap
global g_PSC_ch_eff
global g_PSC_disch_eff
global g_ESS_Op_flag
global g_days
global g_steps
global g_s_period
global g_line_capacity
global g_margin
global g_distance
global g_position
global g_op_unit
global g_op_flag
global g_coef
global g_min_cost
global g_L_critical_best